# Generated by Django 4.2 on 2023-04-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("divulgar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
            ],
        ),
    ]
