# Generated by Django 4.2 on 2023-04-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("divulgar", "0003_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="status",
            field=models.CharField(
                choices=[("P", "Para adoção"), ("A", "Adotado")],
                default="P",
                max_length=1,
            ),
        ),
    ]
